### ISSUE TITLE
Guidelinies proposal sec: Additional for archival concerns

### ISSUE THREAD

**Issue by riedde** [music-encoding/metadata-ig#12]
Needs descriptions: (delegated to @doerners)

- [x] `<exhibHist/>`
- [x] `<physLoc/>`
- [x] `<treatHist/>`
- [x] `<treatSched/>`
- [x] `<acquisition>`
- [x] `<provenance>`

~~`<fingerprint/>`~~

**Comment by doerners** [comment]
This is the first proposal of a description for the `<physLoc>` element. Please consider this a draft, so recommendations for improvement are very welcome :)

The `<physLoc>` element allows to encode any information related to or associated with the physical location of a bibliographic item. This includes, but is not limited to, the name of the holding institution, name or number of the building or room, any shelfmarks, etc. for the purpose of retrieval. The level of detail or machine readability of the encoding is generally at the discretion of the encoder and may vary depending on the information available. The `<physLoc>` element may contain the following MEI-elements:

`<head>`
`<repository>`
`<identifier>`
`<history>`

The `<repository>` element is intended to contain a description of the institution or individual currently holding the bibliographic item. Its content is either extensive prose or structured, and thus better machine readable, information. The `<history>` element on the other hand is a container for additional non-bibliographic details regarding the physical location of an item. It may contain i.a. one of the elements `<acquisition>`, `<exhibHist>` or `<provenance>` to describe any events that coincided with a change of location like exhibitions, change of custody or alike. However, in the case that the bibliographic item does no longer exist or its physical location is unknown, it is generally advised to encode the historical information directly on the `<item>` level. 

The following example shows an encoding of greater level of detail for information about the repository:

```XML
<physLoc>
   <repository auth="ISIL" auth.uri="http://ld.zdb-services.de/resource/organisations/" codedval="DE-1">
      <identifier auth="RISM">D-B</identifier>
      <corpName xml:id="SBB-PK" role="Holding institution">
         <name>Staatsbibliothek zu Berlin – Preußischer Kulturbesitz</name>
         <add>Haus Unter den Linden</add>
         <add>Musikabteilung</add>
      </corpName>
      <address>
         <addrLine>Unter den Linden 8</addrLine>
         <addrLine>
            <postCode>10117</postCode> 
            <geogName auth="geonames" auth.uri="http://www.geonames.org/" codedval="2950159">Berlin</geogName>
         </addrLine>
      </address>
   </repository>
   <identifier type="shelfmark">Mus.ms. Bach P 175</identifier>
</physLoc>
```

**Comment by rettinghaus** [comment]
Great, thank you!

Maybe instead of 

> The following example shows an encoding of greater level of detail for information about the repository:

something like:

The following code snippet shows an example of structured and detailed information about a repository

?

**Comment by doerners** [comment]
Thanks @rettinghaus! Let's discuss that tomorrow with the IG

**Comment by doerners** [comment]
This is a first proposal for a description of the `<exhibHist>` element. 

The `<exhibHist>` element is intended to contain descriptions of one or more public exhibitions of a bibliographic item. Often exhibitions include an additional description in the form of a tag for the public that accompanies the item on display. These descriptions may even be printed in a published exhibition catalogue, so the encoding may also include information about why the object was shown or what was significant about the exhibition. When formulating the encoding, it is at the discretion of the encoder whether to opt for text or more structured information. Text-centred or essayistic encoding is made possible by `<p>` elements in `<exhibHist>`, among others. For more structured encodings, it is recommended to use the `<eventList>` element contained in `<exhibHist>`. Within MEI `<exhibHist>` is conceptually bound to the `item`-level, however, as a child element to `<history>`, `<exhibHist>` is allowed in several places. It is up to the encoder to decide where the information is most appropriate for the particular project or encoding purposes. As best practice, it is recommended that `<exhibHist>` is encoded as a child element of either `<item>` or `<physLoc>`.

**Comment by mss2221** [comment]
> Great, thank you!
> 
> Maybe instead of
> 
> > The following example shows an encoding of greater level of detail for information about the repository:
> 
> something like:
> 
> The following code snippet shows an example of structured and detailed information about a repository
> 
> ?
 another suggestion: 

The following example demonstrates how to structure more detailed information about a repository.

**Comment by doerners** [comment]
This is a first proposal for a description of the `<treatSched>` element.

Similarly to the MEI `<treatHist>` element, the `<treatSched>` element is intended to hold records of conservation activities or treatments, respectively in regard to a bibliographic item. However, in contrast to `<treatHist>`, `<treatSched>` considers records of any anticipated activities rather than a historical account for undergone treatments. This might include any description indicating the quantity and frequency of the accruals. `<treatSched>` furthermore may also be used to indicate that no additions or treatments are to be expected. To that end, `<treatSched>` allows either to opt for text or more structured information when formulating the specific encoding. It is at the discretion of the encoder to decide which specifics of the encoding is most appropriate.

**Comment by irmlindcapelle** [comment]
for me these description are ready for being integrated into the guidelines? than the issue could be closed

**Comment by riedde** [comment]
As you can see above this comment, I added a basic documentation for `<acquisition>` and `<provenance>`. You can [comment the commit](https://github.com/music-encoding/metadata-ig/commit/2632c8f615253b04bef151c3237dade42321624e) if you like.

**Comment by riedde** [comment]
I also have put every text from this proposal to the guidlelines doc.

**Comment by gucl-mu** [comment]
I don't think it is particularly useful to throw provenance information into a <p>. If previous owners are collectors, they usually own several manuscripts and these usually passed to another owner after the death of the former owner. These are sometimes clear sequences or else there are gaps (usually more often, unfortunately). Anyway, it is worthwhile to make such sequences visible. This may also be possible in a <p>, but a structured query is then made more difficult and it does not hurt anyone to mark the date and person separately again (see ex. below)...
I would suggest the following addition/revision:
For better machine readability while retaining the freedom to describe individual processes, it is recommended to store the various ownership relationships of manuscripts in an eventList. For each <event>, i.e. the period of time when a manuscript was in the possession of a person or entity, it is possible to create a <desc> and at the same time mark <date> and <person> separately, as in the following example:
```
<event>
     <date startdate="1900" enddate="1911">1900-1911</date>.
     <persName role="former owner">Charles Malherbe</persName>.
     <desc>From 1900 to 1911, the manuscript was owned by Charles Malherbe.</desc>
</event>
```

**Comment by riedde** [comment]
I absolutely agree, that would be a helpful addition. And I think we can slightly modify this that it works for both provenance and acquisition, because I tried to avoid writing to identical paragraphs.

**Comment by doerners** [comment]
Perfect, thanks :) Closing this now

**Comment by bwbohl** [comment]
@music-encoding/ig-metadata has this made its way to the main repo? Can https://github.com/music-encoding/music-encoding/issues/920 be closed?
