### ISSUE TITLE
Discuss <fingerprint>

### ISSUE THREAD

**Issue by doerners** [music-encoding/metadata-ig#13]
I do not see a big difference in purpose between `<fingerprint>` and `<identifier>`. However, `<identifier>` allows way more child elements than `<fingerprint>`, which only allows textual content. I also would not consider an identifier as a inherent physical property of a resource, thus I think `<fingerprint>` is misplaced in `<physDesc>`. Furthermore `<fingerprint>` is allowed in many places that do not seem sensible but it is not allowed as a direct child of `<fileDesc>`. This does not make sense to me since it might be advantageous to store a checksum for a whole MEI file. I’m not sure if we even need this element, since it might be sufficient to only use `<identifier>`.

**Comment by ahankinson** [comment]
For additional context: https://www.jstor.org/stable/30199939

It seems that 'fingerprinting' is a well-accepted practice in some cataloguing communities, and is typically a transcription of part of the second folio of the book, which makes it an inherent physical property of the item.

**Comment by riedde** [comment]
@ahankinson Thank you for that input. I think we have to check that.
One general problem of the metadata ig and especially of improving chapter 3 of the guidelines is that in our group there are almost philologists, so the view from e.g. librarians is missing. And I noticed, that in different disciplines the definition of what is "physical" is very very different. But collecting these information will make the guidelines even better :)

**Comment by doerners** [comment]
Yes thank you @ahankinson for this insight! I also found the following article, which might add some valuable info: https://doi.org/10.1108/eb026157

From what I understood reading the article @ahankinson linked, the practice of 'fingerprinting' mainly or even only(?) applies to manuscripts. However, the element description of `<fingerprint>` states that it:

>Contains a string that uniquely identifies an item, such as those constructed by combining groups of characters transcribed from specified pages of a printed item or a file's checksum.

Thus, I understand that it is meant for printed (not manuscripts?) as well as digital resources. What is troubling me is that I personally see a difference in purpose of a 'fingerprint' between manuscripts and digital resources. For the manuscripts I understand that the practice of fingerprinting is supposed to uniquely identify a certain manuscript, given the assumption that no two scribes will ever write the same amount of text on a given folio. Therefore the transcription of e.g. the first line of the text proper from the second folio seems a reliable action for identifying a manuscript. On the other hand, I understand checksums in terms of digital preservation practice and thus, as a means to verify that the integrity of a digital file hasn't been compromised, e.g. through file transfer processes, so that the file is still intact and useable.  I would argue that the purpose is somewhat different from merely identifying a file.

This leads me to think that we might should discuss more what we want to achieve with this element. I think this would also help to come up with a good description for the guidelines.

**Comment by ahankinson** [comment]
Perhaps also of interest to help the discussions: The MARC21 spec defines a fingerprint field, 026: https://www.loc.gov/marc/bibliographic/bd026.html

There are several recognized fingerprint structures that are available here: https://www.loc.gov/standards/sourcelist/fingerprint.html

RISM uses this field to record identifying data about printed books.

**Comment by doerners** [comment]
From what I read from the MARC specification the standard calls the field 026 `fingerprint identifier`, so I understand it indeed to be a sort of identifier. Its field definition and scope also states that it is:

> Used to assist in the identification of antiquarian books by recording information comprising groups of characters taken from specified positions on specified pages of the book, in accordance with the principles laid down in various published guidelines. 

I think one can argue that a fingerprint is indeed suitable for manuscripts as well as printed books, although maybe not recently printed ones. What I found surprising is that MARC does not subsume this under physical descriptions since those are stored in the 3XX fields, see: https://www.loc.gov/marc/bibliographic/bd3xx.html
Is it thus fair to assume that a fingerprint is not considered a physical description within the MARC universe?

On the other hand 026 does not give any information regarding checksums. If we take a look at the [PREMIS standard](https://www.loc.gov/standards/premis/), however, there we can find a designated element for storing information on checksums, namely the `fixity` element, see: https://www.loc.gov/standards/premis/v3/premis-3-0-final.pdf, p.59–60 and p.258

As I understand the element description of `<fingerprint>` it is, as of right now, a mixture of both an element to store information regarding fingerprint identifiers and checksums. I'm not quite sure if it is a good idea to have it this way.  I'm also not sure if we need a separate `<fingerprint>` element, wouldn't it be possible and might also sensible to encode those information within the `<identifier>` element that exists in MEI?
I could imagine the encoding to look similar to: <identifier type="fingerprint">some identifying text</identifier>

**Comment by riedde** [comment]
Results from todays IG-Meeting:
Nobody answered the calls for usage examples of this element. The only place we found it was [here](https://github.com/music-encoding/encoding-tools/blob/cb6bb19a75b983617f56cb4aad4eaaf9cb8558a5/mei2010To2012/mei2010To2012.xsl#L216) with the comment: "use of mei:fingerprint deprecated".

So the ig is going to open an issue in the music-encoding repo with the proposal to delete `<fingerprint>`.
