### ISSUE TITLE
Discuss <provenance> and <acquisition>

### ISSUE THREAD

**Issue by doerners** [music-encoding/metadata-ig#17]
It seems to me that `<provenance>` and `<acquisition>` aren't described in the guidelines, yet. We should discuss where to put them. On a quick thought I think it might be best to put them under the new section 3.7.3 Archival concerns. 

Furthermore, I would also like to discuss maybe renaming section 3.7.3 since to me it seems that all the elements are history-like elements and the name might should reflect that. Maybe the name could be something like `Historical Account`

**Comment by riedde** [comment]
During todays meeting the ic accepted the proposal to rename the guidline chapter "archival concerns" to " historical account". Further it was decided to add a documentation of `<provenance>` and `<acquisition>`, as proposed, to this chapter.
The notice about the missing model class was noticed by the group, but is an already opened issue at the ODD group, so it will not longer be discussed here.
Thanks to @doerners to bring this up and for the solid content base for the discussion!
