### ISSUE TITLE
move older agendas from project to wiki

### ISSUE THREAD

**Issue by riedde** [music-encoding/metadata-ig#24]
The columns and cards in the project are good for working on things, but can't be used for archiving. So the documentation of the IG meetings should be moved to the wiki by time.

This idea came up during a passed meeting. This issue should prevent that this task will be forgotten.

**Comment by doerners** [comment]
Seems like you have been working on this @riedde, thanks a lot! To me the wiki looks good already, so I was wondering if this issue could be closed?

**Comment by riedde** [comment]
Thanks! I just forgot to close this!
